### ISSUE TITLE
[Bug]: too many ducks/quacklings spawning

### ISSUE THREAD

**Issue by deadtoxaris** [ThatGravyBoat/Duckling#24]
### Bug Description

too many ducks are spawning at any biome given.. we downloaded the mod and installed it and not 40 minutes in and we were surrounded by approximately 15-20 ducks.. as time goes by there are more and more.. quacklings are becoming a massive problem too, but they are biome-dependent but still way to many spawns at it.. would be nice to have config option to reduce them (spawn rate) or just put it directly at files so people don't need to reduce it in config files by themselves. please consider it because server lags are becoming big problem !
thanks

### Version

1.19

### Mod Loader Version

0.14.9

### Mod Loader

Fabric

**Comment by ThatGravyBoat** [comment]
well seeing as ducks can only spawn in rivers it sounds like there is a mod in your instance that is screwing up spawns. I have played with the mod on my own servers and never had any issues with ducks spawning too often. Make sure to check which mods you have installed.

**Comment by ThatGravyBoat** [comment]
they also can only spawn in water too.

**Comment by ThatGravyBoat** [comment]
and with vanilla worldgen for example it shares the same spawn pool as salmon which means max only 20 mobs in that pool can spawn and ducks have a 50/50 with salmon of spawning but salmon can spawn up to 5 while ducks spawn up to 3 so there being 20 ducks makes even less sense and rivers actually have less spawn change of salmon and ducks because of a vanilla feature that reduces the spawn chance of ambient water mobs.
