### ISSUE TITLE
[Feature Request & Bug]: Config file to control mob spawns and Quackling inventory

### ISSUE THREAD

**Issue by Toilet-Lord** [ThatGravyBoat/Duckling#9]
### Is your feature request related to a problem?

There are WAYYY too many Quacklings
![2022-06-17_13 07 14](https://user-images.githubusercontent.com/76745705/174345625-817655ee-7c62-46dc-8bcc-010d2c0cdc5d.png)

_(talking about the code below)_ I don't understand since, if I read this well (I am not a programmer), the Quacklings should have a 0.2% chance to spawn right?
So this could also be a bug the way I see it?? 
_(I really dont wanna sound like a smart ass by saying this, it really is a genuine question)_

in MobSpawn.class
```
public class ModSpawns {
    public static void addSpawns() {
        CommonServices.REGISTRY.addEntityToBiome(class_6908.field_36511, new SpawnData((class_1299)ModEntities.DUCK.get(), class_1311.field_24460, 5, 3, 4, precipitation -> !precipitation.equals((Object)class_1959.class_1963.field_9383)));
        CommonServices.REGISTRY.addEntityToBiome(class_6908.field_36532, new SpawnData((class_1299)ModEntities.QUACKLING.get(), class_1311.field_6300, 1, 0, 1));
    }
```

### Solution(s)

A config file for Ducklings & Quacklings spawns and optionally a way to change the items Quacklings sell

### Describe alternatives you've considered

A mod-menu integration?

### Mod Version

2.0.0

### Mod Loader Version

1.19 - 0.14.7 Fabric

### Mod Loader

Fabric

**Comment by Toilet-Lord** [comment]
There seems to be an issue with mob spawning
I left my game running while I was writing the Feature suggestion and the problem has become worse.
![2022-06-17_13 19 37](https://user-images.githubusercontent.com/76745705/174347784-0aaab576-3c09-4381-b62a-39c4730c3d40.png)

The mob spawns seems to be closely tied to the amount of time you spend in an area

**Comment by ThatGravyBoat** [comment]
that 1 means it has a weight of 1 which means that combined with all other mobs in that category it has the lowest so let us say there is another mob that has a weight of 3 then that means the quacking has a spawn chance of 25% but after all that it then has another 50% chance to also spawn because I set the min spawn amount to 0 and the max to 1 and then after all that I have another check for if a random number between 0 and 250 is 0 so, therefore, adding another chance of  0.4% so they should technically be never really spawning that much.

But I will be changing the category to the normal creatures instead of water creatures so that there is more stuff in the spawn category to decrease the quacking spawn rate to a 0.002% chance to spawn or possibly a little higher because I need to take into account that other mods mobs also change the number.

Later today there will be an update to a "fix" for the spawns

And also the thing to change the Quacklings inventory is that it is just a fisherman villager so you can find a mod that changes normal villager trades.
And to control the spawns is a forge-only feature right now as forge provides it by default and I would have to explicitly write it for fabric.

**Comment by Toilet-Lord** [comment]
Wow thanks for the throughout response! I really appreciate it!

I'll be looking forward to the update!
Keep the nice work <3
